import research from './research.json';
import { BookOpen, Download } from 'lucide-react';

const n = (value: number, digits = 2) => new Intl.NumberFormat('id-ID', { maximumFractionDigits: digits }).format(value);

export default function ForecastResearch() {
  return <section className="card research-evaluation">
    <div className="section-head"><div><span className="control-label">RESEARCH / FORECASTING</span><h3>Hasil model, dengan konteksnya.</h3><p>Evaluasi test 2019–2024 · forecast akhir dilatih ulang sampai 2024</p></div><a className="outline-button" href="/research/forecast-notebook-2025-2030.csv" download><Download size={15} /> Semua hasil CSV</a></div>
    <div className="research-metric-grid"><div><span>MLP produksi · MAPE test</span><strong>{n(research.forecast.riceMetrics[0]['MAPE (%)'])}<small>%</small></strong><p>Lag 5 · hidden 16 · α 0,01</p></div><div><span>LSTM populasi · MAPE test</span><strong>{n(research.forecast.populationMetrics[0]['MAPE (%)'])}<small>%</small></strong><p>Lag 3 · hidden 8 · 250 epochs</p></div><div><span>MLP populasi · MAPE test</span><strong>{n(research.forecast.populationMetrics[1]['MAPE (%)'])}<small>%</small></strong><p>Lag 3 · hidden 16 · α 0,01</p></div></div>
    <div className="table-scroll"><table><thead><tr><th>TARGET / MODEL</th><th>MAPE TEST</th><th>RMSE</th><th>MAE</th><th>SATUAN GALAT</th></tr></thead><tbody>{[...research.forecast.riceMetrics.map(row => ({...row, target: 'Padi', unit: 'ton gabah'})), ...research.forecast.populationMetrics.map(row => ({...row, target: 'Populasi', unit: 'jiwa'}))].map(row => <tr key={row.target + row.Model}><td>{row.target} · {row.Model}</td><td>{n(row['MAPE (%)'])}%</td><td>{n(row.RMSE, 0)}</td><td>{n(row.MAE, 0)}</td><td>{row.unit}</td></tr>)}</tbody></table></div>
    <div className="research-notes"><BookOpen size={20} /><div><strong>MLP dan LSTM memiliki hasil yang berbeda.</strong><p>Produksi 2030: MLP {n(research.forecast.future.rice.MLP[5].value / 1e6)} juta ton; LSTM {n(research.forecast.future.rice.LSTM[5].value / 1e6)} juta ton. Angka 199,33 juta ton pada infografis sesuai LSTM. MAPE 0,93% adalah evaluasi MLP produksi, bukan LSTM. Pemilihan berdasarkan validasi produksi 2013–2018 justru mengunggulkan XGBoost (MAPE {n(research.forecast.validation[0]['Validation MAPE (%)'])}%); forecast XGBoost 2025–2030 tidak tersimpan.</p><p>Model memakai MinMaxScaler pada train, jendela lag, dan prediksi rekursif. Train produksi 1961–2018; train populasi 1950–2018. Metrik mengacu ke hasil notebook asli dan tidak berlaku untuk simulasi tekanan panen atau proyeksi negara.</p><p>Website menyajikan tabel forecast tersimpan, dengan pembulatan satu ton/jiwa. Riwayat grafik berasal dari snapshot OWID; nilai dasar 2024 agregat diselaraskan ke notebook. Nama agregat produksi di file asli: “Total 10 Negara”; komposisi agregat tidak dapat diverifikasi tanpa CSV asli.</p></div></div>
  </section>;
}
