import ResearchFigure from './ResearchFigure';
import { t, getLocale } from './i18n';
import { useEffect, useMemo, useState } from 'react';
import { Activity, BookOpen, Download, Expand, Layers3, MapPin, Sprout, X } from 'lucide-react';
import { CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { geoMercator, geoPath } from 'd3-geo';
import type { FeatureCollection } from 'geojson';
import research from './research.json';
import { countries } from './model.mjs';
import { spatioRows, spatioTotal } from './research-model.mjs';

type AreaRow = { code: string; name: string; mean: number; lower: number; upper: number; width: number };
type Layer = 'mean' | 'lower' | 'upper' | 'width';
const n = (value: number, digits = 0) => new Intl.NumberFormat(getLocale(), { maximumFractionDigits: digits }).format(value);
const names: Record<Layer, string> = { mean: 'Estimasi luas panen', lower: 'Batas bawah', upper: 'Batas atas', width: 'Lebar interval' };
const scenarios = { ssp245: 'SSP2-4.5', ssp585: 'SSP5-8.5' };

function AreaMap({ rows, selected, layer, onSelect }: { rows: AreaRow[]; selected: string; layer: Layer; onSelect: (code: string) => void }) {
  const [geo, setGeo] = useState<FeatureCollection | null>(null);
  const [error, setError] = useState(false);
  const projection = useMemo(() => geoMercator().center([117, 9]).scale(430).translate([270, 164]), []);
  const path = geoPath(projection);
  useEffect(() => { fetch('/sea.geojson').then(r => { if (!r.ok) throw Error('map'); return r.json(); }).then(setGeo).catch(() => setError(true)); }, []);
  const fill = (row?: AreaRow) => {
    if (!row) return '#e3e8df';
    const value = row[layer];
    return value >= 5e6 ? '#285e48' : value >= 2e6 ? '#598d6b' : value >= 5e5 ? '#8bb78e' : value >= 1e5 ? '#b6cf9b' : '#dce8bd';
  };
  return <div className="area-map"><div className="map-tools"><span><MapPin size={13} />{t("10 negara · hasil ringkasan GADM")}</span><span>{t("2030 / hektare")}</span></div>{error ? <p className="empty-state">{t("Peta tidak tersedia; tabel negara tetap dapat digunakan.")}</p> : !geo ? <p className="empty-state">{t("Memuat batas negara…")}</p> : <svg viewBox="0 0 540 335" aria-label={t("Peta {p0} per negara 2030", {p0: names[layer]})}>
    <rect width="540" height="335" rx="12" fill="#edf2e9" />
    {geo.features.map(feature => { const code = feature.properties?.code; const row = rows.find(r => r.code === code); return <path key={code} d={path(feature) || ''} fill={fill(row)} stroke={selected === code ? '#143e31' : '#fff'} strokeWidth={selected === code ? 2.5 : 1.2} className={row ? 'map-country' : ''} role={row ? 'button' : undefined} tabIndex={row ? 0 : undefined} aria-label={row ? t("Luas panen {p0}", {p0: row.name}) : undefined} onClick={() => row && onSelect(code)} onKeyDown={e => { if (row && ['Enter', ' '].includes(e.key)) { e.preventDefault(); onSelect(code); } }}><title>{row ? t("{p0}: {p1} ha", {p0: row.name, p1: n(row[layer])}) : feature.properties?.name}</title></path>; })}
    {rows.map(row => { const country = countries.find(c => c.code === row.code)!; const xy = projection(country.label as [number, number])!; return <text key={row.code} x={xy[0]} y={xy[1]} textAnchor="middle" className="area-map-label" pointerEvents="none">{t(country.name)}</text>; })}
    {rows.filter(r => ['SGP', 'BRN'].includes(r.code)).map(row => { const country = countries.find(c => c.code === row.code)!; const xy = projection([country.lon, country.lat])!; return <circle key={row.code} cx={xy[0]} cy={xy[1]} r="5" fill={fill(row)} stroke="#fff" role="button" tabIndex={0} aria-label={t("Titik luas panen {p0}", {p0: country.name})} onClick={() => onSelect(row.code)} onKeyDown={e => { if (['Enter', ' '].includes(e.key)) { e.preventDefault(); onSelect(row.code); } }}><title>{t(country.name)}: {n(row[layer], 2)} {t("ha")}</title></circle>; })}
  </svg>}<div className="area-legend"><span><i style={{background:'#dce8bd'}} />{t("&lt;100 rb")}</span><span><i style={{background:'#b6cf9b'}} />{t("100–500 rb")}</span><span><i style={{background:'#8bb78e'}} />{t("0,5–2 jt")}</span><span><i style={{background:'#598d6b'}} />{t("2–5 jt")}</span><span><i style={{background:'#285e48'}} />{t("≥5 jt ha")}</span></div></div>;
}

export default function SpatioTemporal() {
  const [scenario, setScenario] = useState<'ssp245' | 'ssp585'>('ssp245');
  const [selected, setSelected] = useState('ALL');
  const [layer, setLayer] = useState<Layer>('mean');
  const [figure, setFigure] = useState('historical');
  const [expanded, setExpanded] = useState(false);
  const rows: AreaRow[] = spatioRows(research, scenario);
  const selectedRow = rows.find(row => row.code === selected);
  const total = selectedRow || spatioTotal(rows);
  const other: AreaRow[] = spatioRows(research, scenario === 'ssp245' ? 'ssp585' : 'ssp245');
  const otherTotal = selectedRow ? other.find(row => row.code === selected)! : spatioTotal(other);
  const item = research.spatio.figures.find(item => item.name === figure)!;
  const metrics = research.spatio.metrics;
  const meanMoran = research.spatio.residuals.reduce((sum, row) => sum + row.moran_i, 0) / research.spatio.residuals.length;
  useEffect(() => {
    if (!expanded) return;
    const previous = document.activeElement as HTMLElement | null;
    const oldOverflow = document.body.style.overflow;
    document.body.style.overflow = 'hidden';
    const button = document.querySelector<HTMLButtonElement>('.figure-dialog button'); button?.focus();
    const close = (event: KeyboardEvent) => { if (event.key === 'Escape') setExpanded(false); if (event.key === 'Tab') { event.preventDefault(); button?.focus(); } };
    document.addEventListener('keydown', close);
    return () => { document.body.style.overflow = oldOverflow; document.removeEventListener('keydown', close); previous?.focus(); };
  }, [expanded]);
  const exportSelected = () => {
    const filtered = selected === 'ALL' ? rows : rows.filter(row => row.code === selected);
    const csv = ['scenario,year,country,estimated_harvested_area_ha,conditional_lower_ha,conditional_upper_ha', ...filtered.map(row => [scenario, 2030, row.code, row.mean, row.lower, row.upper].join(','))].join('\r\n');
    const url = URL.createObjectURL(new Blob(['\uFEFF'+csv], {type:'text/csv;charset=utf-8'}));
    const anchor = document.createElement('a'); anchor.href=url; anchor.download=`riceguard-spatio-${scenario}-${selected}-2030.csv`; anchor.click(); URL.revokeObjectURL(url);
  };
  return <div className="spatio-research">
    <section className="research-banner"><div><span className="control-label"><Layers3 size={15} /> {t("SPATIO-TEMPORAL / GLORICE")}</span><h2>{t("Luas panen. Ruang. Waktu.")}</h2><p>{t("Harvested-area outlook · 2030")}</p></div><span className="research-status"><i />{t("OUTPUT TERSIMPAN")}</span></section>
    <div className="card spatio-controls"><label>{t("Skenario iklim")}<select aria-label={t("Skenario iklim spasial")} value={scenario} onChange={e => setScenario(e.target.value as typeof scenario)}><option value="ssp245">{t("SSP2-4.5 · menengah")}</option><option value="ssp585">{t("SSP5-8.5 · emisi tinggi")}</option></select></label><label>{t("Wilayah analisis")}<select aria-label={t("Wilayah spatio-temporal")} value={selected} onChange={e => setSelected(e.target.value)}><option value="ALL">{t("10 covered countries")}</option>{rows.map(row => <option key={row.code} value={row.code}>{t(countries.find(c => c.code === row.code)?.name)}</option>)}</select></label><label>{t("Layer peta")}<select aria-label={t("Layer luas panen")} value={layer} onChange={e => setLayer(e.target.value as Layer)}>{Object.entries(names).map(([key, label]) => <option key={key} value={key}>{t(label)}</option>)}</select></label><button className="outline-button" onClick={exportSelected}><Download size={15} /> {t("Ekspor pilihan")}</button></div>
    <div className="spatio-kpis"><div className="card"><span>{t("Estimasi luas panen · 2030")}</span><strong>{n(total.mean/1e6, 3)}<small>{t("juta ha")}</small></strong><p>{selectedRow ? t(countries.find(c => c.code === selected)?.name) : t("10 covered ASEAN countries")} · {scenarios[scenario]}</p></div><div className="card"><span>{t("Interval bersyarat · 2030")}</span><strong>{n(total.lower/1e6, 3)} – {n(total.upper/1e6, 3)}<small>{t("juta ha")}</small></strong><p>{selectedRow ? t("Batas hasil posterior aproksimatif") : t("Jumlah batas negara; bukan interval posterior total")}</p></div><div className="card"><span>{t("Perbedaan skenario alternatif")}</span><strong>{n((otherTotal.mean / total.mean - 1)*100, 3)}<small>%</small></strong><p>{t("Alternatif")}{' '}{scenario === 'ssp245' ? t("SSP5-8.5") : t("SSP2-4.5")} {t("relatif terhadap pilihan")}</p></div></div>
    <div className="spatio-map-grid"><section className="card"><div className="section-head"><div><h3>{t("Distribusi luas panen 2030")}</h3><p>{t(names[layer])} · {scenarios[scenario]} {t("· ringkasan negara")}</p></div><button className="text-button" onClick={() => setSelected('ALL')}>{t("Reset wilayah")}</button></div><AreaMap rows={rows} selected={selected} layer={layer} onSelect={setSelected} /></section><section className="card spatio-detail"><span className="control-label">{t("WILAYAH TERPILIH")}</span><h3>{selectedRow ? t(countries.find(c => c.code === selected)?.name) : t("ASEAN · 10 negara")}</h3><Sprout size={33} strokeWidth={1.2} /><div className="detail-row"><span>{t("Estimasi")}</span><strong>{n(total.mean, 2)} {t("ha")}</strong></div><div className="detail-row"><span>{t("Batas bawah")}</span><strong>{n(total.lower, 2)} {t("ha")}</strong></div><div className="detail-row"><span>{t("Batas atas")}</span><strong>{n(total.upper, 2)} {t("ha")}</strong></div><p>{t("Sel model 2° dialokasikan menurut fraksi irisan batas GADM pada proyeksi equal-area. Geometri tampilan memakai Natural Earth.")}</p>{['SGP','BRN'].includes(selected) && <p className="small-country-note">{t("Estimasi negara kecil sangat sensitif terhadap grid kasar dan batas wilayah. Gunakan untuk membaca hasil model.")}</p>}<p className="fine-print">{t("Luas panen (ha) berbeda dari produksi gabah (ton). Hasil ini tidak langsung menentukan risiko atau defisit pangan.")}</p></section></div>
    <section className="card research-figures"><div className="section-head"><div><h3>{t("Jejak perubahan dari raster asli")}</h3><p>{t("Historical harvested area and the 2030 outlook")}</p></div><button className="icon-button" aria-label={t("Perbesar gambar penelitian")} onClick={() => setExpanded(true)}><Expand size={18} /></button></div><div className="figure-tabs" role="group" aria-label={t("Pilihan visual penelitian")}>{research.spatio.figures.map(image => <button key={image.name} className={figure === image.name ? 'selected' : ''} onClick={() => setFigure(image.name)}>{image.name === 'historical' ? '1961 → 2021' : image.name === 'fine-2030' ? t("2030 · 5 arcminute") : image.name === 'uncertainty' ? t("2030 · Ketidakpastian") : t("Perbandingan negara")}</button>)}</div><button className="figure-preview" aria-label={t("Perbesar {p0}", {p0: item.title})} onClick={() => setExpanded(true)}><ResearchFigure figure={item} /></button><div className="figure-caption"><p>{figure === 'historical' ? t("GloRice intensive harvested area: peta 1961 dan 2021 dengan skala log yang sama.") : figure === 'fine-2030' ? t("Pola 5 arcminute adalah disagregasi visual hasil grid 2° mengikuti dukungan luas panen GloRice 2021. Bukan inferensi baru pada piksel atau prediksi lokasi sawah baru.") : figure === 'uncertainty' ? t("Grid model 2°: dua skenario 2030 dan lebar interval SSP2-4.5. Interval bersyarat belum mencakup seluruh ketidakpastian iklim.") : t("Ringkasan negara berdasarkan fraksi irisan sel 2° dan batas GADM.")}</p><a href={item.path} download className="text-button"><Download size={14} /> {t("PNG asli")}</a></div></section>
    <section className="card research-evaluation"><div className="section-head"><div><span className="control-label">{t("MODEL / VALIDATION")}</span><h3>{t("Kinerja yang dapat diperiksa")}</h3><p>{t("Latih 1981–2011 · forward holdout 2012–2021 ·")}{' '}{n(metrics.n_test)} {t("observasi test")}</p></div><Activity size={20} /></div><div className="research-metric-grid"><div><span>{t("R² pada holdout")}</span><strong>{n(metrics.r2, 4)}</strong><p>{t("Koefisien determinasi · bukan % akurasi")}</p></div><div><span>{t("MAE luas panen")}</span><strong>{n(metrics.mae_ha)}<small>{t("ha")}</small></strong><p>{t("RMSE")}{' '}{n(metrics.rmse_ha)} {t("ha")}</p></div><div><span>{t("Rerata Moran’s I residual")}</span><strong>{n(meanMoran, 3)}</strong><p>{t("p = 0,005 per tahun · klaster masih tersisa")}</p></div></div><div className="residual-chart" role="img" aria-label={t("Grafik Moran I residual 2012 sampai 2021")}><ResponsiveContainer width="100%" height="100%"><LineChart data={research.spatio.residuals} margin={{left:0,right:25,top:15,bottom:10}}><CartesianGrid stroke="#e5e9e1" strokeDasharray="3 5" vertical={false}/><XAxis dataKey="year" tick={{fontSize:11}} axisLine={false} tickLine={false}/><YAxis domain={[0,1]} tick={{fontSize:11}} axisLine={false} tickLine={false}/><Tooltip formatter={v => [n(Number(v),4),'Moran’s I']}/><Line dataKey="moran_i" stroke="#548467" strokeWidth={2.4} dot={{r:4}} isAnimationActive={false}/></LineChart></ResponsiveContainer></div><div className="research-notes"><BookOpen size={19}/><div><strong>{t("R² tinggi tetap disertai pola residual spasial.")}</strong><p>{t("Moran’s I positif menunjukkan galat yang masih berkelompok secara spasial. Bias aktual − prediksi:")}{' '}{n(metrics.bias_actual_minus_pred_ha)} {t("ha; model cenderung melebihkan luas panen pada holdout. Presence ROC AUC =")}{' '}{n(metrics.presence_roc_auc, 2)}.</p><p>{t("The projection uses GloRice data from 1981–2021 and one climate model, ACCESS-CM2. The 2030 outlook represents average climate conditions in 2021–2040. The ranges do not capture all climate uncertainty.")}</p></div></div></section>
    <section className="card research-country-table"><div className="section-head"><div><h3>{t("Ringkasan negara ·")}{' '}{scenarios[scenario]}</h3><p>{t("2030 · hektare · klik negara untuk memeriksa hasil")}</p></div><a className="text-button" href="/research/spatio-countries-2030.csv" download><Download size={15}/> {t("Kedua skenario")}</a></div><div className="table-scroll"><table><thead><tr><th>{t("NEGARA")}</th><th>{t("ESTIMASI")}</th><th>{t("BATAS BAWAH")}</th><th>{t("BATAS ATAS")}</th><th>{t("LEBAR INTERVAL")}</th></tr></thead><tbody>{rows.map(row => <tr key={row.code} className={selected === row.code ? 'selected-row' : ''}><td><button className="country-link" onClick={() => setSelected(row.code)}>{countries.find(c => c.code === row.code)?.flag} {t(countries.find(c => c.code === row.code)?.name)}</button></td><td>{n(row.mean,2)}</td><td>{n(row.lower,2)}</td><td>{n(row.upper,2)}</td><td>{n(row.width,2)}</td></tr>)}</tbody></table></div></section>
    <div className="note-card"><Layers3 size={21}/><div><strong>{t("Coverage and interpretation.")}</strong><p>{t("This analysis covers 10 countries, including Singapore and Brunei; Timor-Leste is not covered. Country estimates total")}{' '}{n(spatioTotal(rows).mean/1e6,2)} {t("juta ha berbeda dari seluruh grid")}{' '}{n(research.spatio.gridSummary.find(r => r.scenario === scenario)!.total_predicted_area_ha/1e6,2)} {t("juta ha karena grid juga meliputi daratan di luar ASEAN. Penjumlahan batas negara bukan interval posterior total kawasan.")}</p><p>{t("Maps show the spatial pattern of harvested area. Interactive values represent country-level estimates. Small countries are especially sensitive to the map resolution.")}</p></div></div>
    {expanded && <div className="modal-backdrop" onClick={() => setExpanded(false)}><div className="figure-dialog" role="dialog" aria-modal="true" aria-label={t(item.title)} onClick={e => e.stopPropagation()}><div><h3>{t(item.title)}</h3><button className="icon-button" aria-label={t("Tutup gambar penelitian")} onClick={() => setExpanded(false)}><X size={22}/></button></div><ResearchFigure figure={item}/></div></div>}
  </div>;
}
