import { t, getLocale } from './i18n';
import { useEffect, useId, useMemo, useState } from 'react';
import { Activity, ChevronLeft, ChevronRight, Download, Layers3, LoaderCircle, MapPin, Pause, Play, Sprout } from 'lucide-react';
import { CartesianGrid, Line, LineChart, ReferenceLine, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { geoEquirectangular, geoPath } from 'd3-geo';
import type { FeatureCollection } from 'geojson';
import { countries } from './model.mjs';
import { annualRows, annualTotal, timelineSeries, timelineCsv } from './spatio-timeline.mjs';
import type { SpatioSelection } from './RiceGuardAI';

type Layer = 'mean' | 'lower' | 'upper' | 'width';
type Row = {code:string;mean:number;lower:number|null;upper:number|null;width:number|null};
type Frame = {year:number;kind:'historical'|'projected';scenario:string|null;countries:Row[];raster:string};
type Timeline = {startYear:number;endYear:number;lastHistoricalYear:number;frames:Frame[];extent:number[];rasterScale:{minimum:number;maximum:number;type:string};metrics:{r2:number;mae_ha:number;rmse_ha:number;n_test:number};model:{name:string;gridDegrees:number;cellCount:number;rho:number;refit:string};sources:{name:string;url:string}[]};
const n=(value:number|null|undefined,digits=0)=>value==null?'—':new Intl.NumberFormat(getLocale(),{maximumFractionDigits:digits}).format(value);
const countryName=(code:string)=>t(countries.find(country=>country.code===code)?.name||code);
const layerNames:Record<Layer,string>={mean:'Harvested area',lower:'Lower estimate',upper:'Upper estimate',width:'Uncertainty range width'};

function AnnualMap({data,frame,rows,layer,selected,onSelect}:{data:Timeline;frame:Frame;rows:Row[];layer:Layer;selected:string;onSelect:(code:string)=>void}) {
 const [geo,setGeo]=useState<FeatureCollection|null>(null);const [failed,setFailed]=useState(false);const [rasterError,setRasterError]=useState(false);const clipId=useId().replaceAll(':','');
 useEffect(()=>{let live=true;fetch('/research/gadm-spatio.geojson').then(response=>{if(!response.ok)throw Error('boundaries');return response.json()}).then(result=>{if(live)setGeo(result)}).catch(()=>{if(live)setFailed(true)});return()=>{live=false}},[]);
 const [west,east,south,north]=data.extent;const width=620,height=width*(north-south)/(east-west);
 const projection=useMemo(()=>geoEquirectangular().center([(west+east)/2,(north+south)/2]).scale(width/((east-west)*Math.PI/180)).translate([width/2,height/2]),[west,east,south,north,height]);
 // Boundaries and label positions depend on geometry, not the selected year or layer.
 const boundaries=useMemo(()=>{
  const path=geoPath(projection);
  return geo?.features.map(feature=>{
   const code=String(feature.properties?.code);
   const country=countries.find(country=>country.code===code);
   return {code,d:path(feature)||'',label:country?projection(country.label as [number,number]):null};
  })||[];
 },[geo,projection]);
 const raster=frame.kind==='historical'?frame.raster:frame.raster.replace('-mean.png',`-${layer}.png`);
 useEffect(()=>setRasterError(false),[raster]);
 return <div className="area-map annual-area-map"><div className="map-tools"><span><MapPin size={13}/>{t('10 covered countries')}</span><span>{frame.year} · {t(layerNames[layer])}</span></div>{failed?<p className="empty-state">{t('The map is unavailable. Country values remain available below.')}</p>:!geo?<p className="empty-state"><LoaderCircle className="spin" size={18}/>{t('Loading annual map…')}</p>:<svg viewBox={`0 0 ${width} ${height}`} role="group" aria-label={t('Harvested-area map for {p0}',{p0:frame.year})}>
 <defs><clipPath id={clipId}>{boundaries.map(boundary=><path key={boundary.code} d={boundary.d}/>)}</clipPath></defs><rect width={width} height={height} fill="#edf2f4" rx="9"/>
 {!rasterError&&<image href={raster} width={width} height={height} clipPath={`url(#${clipId})`} onError={()=>setRasterError(true)}/>}
 {boundaries.map(({code,d})=>{const row=rows.find(row=>row.code===code);return <path key={code} d={d} fill={selected===code?'#3a7e6b18':'transparent'} stroke={selected===code?'#1e513d':'#819889'} strokeWidth={selected===code?2:0.7} className="map-country" tabIndex={0} role="button" aria-label={t('Select {p0}',{p0:countryName(code)})} onClick={()=>onSelect(code)} onKeyDown={event=>{if(['Enter',' '].includes(event.key)){event.preventDefault();onSelect(code)}}}><title>{countryName(code)} · {frame.year}: {n(row?.[layer],2)} ha</title></path>})}
 {boundaries.map(({code,label})=>label&&rows.some(row=>row.code===code)?<text key={code} x={label[0]} y={label[1]} textAnchor="middle" pointerEvents="none" className="area-map-label">{countryName(code)}</text>:null)}
 </svg>}{rasterError&&<p role="alert" className="inline-error">{t('This year’s map could not be loaded. The figures and table are still available.')}</p>}
 <div className="annual-map-legend"><span>{t('Smaller area')}</span><i/><span>{t('Larger area')}</span></div><p className="fine-print">{t('Map colors use a fixed scale across years. Future detail follows the 2021 rice-field pattern.')}</p></div>;
}

export default function SpatioTemporal({onSelectionChange}:{onSelectionChange?:(selection:SpatioSelection)=>void}) {
 const [data,setData]=useState<Timeline|null>(null);const [failed,setFailed]=useState(false);const [reload,setReload]=useState(0);const [year,setYear]=useState(2021);const [scenario,setScenario]=useState('ssp245');const [selected,setSelected]=useState('ALL');const [layer,setLayer]=useState<Layer>('mean');const [playing,setPlaying]=useState(false);
 useEffect(()=>{let live=true;setFailed(false);fetch('/research/spatio-timeline.json').then(response=>{if(!response.ok)throw Error('timeline');return response.json()}).then(result=>{if(live)setData(result)}).catch(()=>{if(live)setFailed(true)});return()=>{live=false}},[reload]);
 useEffect(()=>{if(!playing||!data)return;const timer=setInterval(()=>setYear(previous=>previous>=data.endYear?data.startYear:previous+1),1100);return()=>clearInterval(timer)},[playing,data]);
 useEffect(()=>{if(data&&year<=data.lastHistoricalYear&&layer!=='mean')setLayer('mean')},[year,data,layer]);
 useEffect(()=>{onSelectionChange?.({year,scenario,countryCode:selected,layer:year<=2021?'mean':layer});},[year,scenario,selected,layer,onSelectionChange]);
 const frame=useMemo(()=>data?.frames.find(frame=>frame.year===year&&(frame.kind==='historical'||frame.scenario===scenario)),[data,year,scenario]);
 const rows:Row[]=useMemo(()=>data?annualRows(data,year,scenario):[],[data,year,scenario]);const picked=rows.find(row=>row.code===selected);const regionalTotal=useMemo(()=>annualTotal(rows),[rows]);const total=picked||regionalTotal;const historical=frame?.kind==='historical';
 // Moving the year marker does not change the full historical/projected series.
 const series=useMemo(()=>data?timelineSeries(data,scenario,selected):[],[data,scenario,selected]);const previous:Row[]=useMemo(()=>data?annualRows(data,year-1,scenario):[],[data,year,scenario]);const previousRegionalTotal=useMemo(()=>annualTotal(previous),[previous]);const previousTotal=selected==='ALL'?previousRegionalTotal:previous.find(row=>row.code===selected);const change=previousTotal&&previousTotal.mean>0?(total.mean/previousTotal.mean-1)*100:null;
 const chooseYear=(next:number)=>{setPlaying(false);setYear(next)};
 const exportSelected=()=>{if(!data)return;const csv=timelineCsv(data,year,scenario,selected);const url=URL.createObjectURL(new Blob(['\uFEFF'+csv],{type:'text/csv;charset=utf-8'}));const anchor=document.createElement('a');anchor.href=url;anchor.download=`riceguard-spatio-${selected}-${year}-${historical?'historical':scenario}.csv`;anchor.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
 if(!data)return <section className="card annual-loading">{failed?<><Layers3 size={28}/><h3>{t('Annual results could not be loaded.')}</h3><p>{t('Check your connection to the local server and try again.')}</p><button className="outline-button" onClick={()=>setReload(reload+1)}>{t('Try again')}</button></>:<><LoaderCircle className="spin" size={24}/><p>{t('Loading annual harvested-area results…')}</p></>}</section>;
 if(!frame)return <section className="card annual-loading"><p>{t('No results are available for the selected year.')}</p></section>;
 const historicalPercent=(data.lastHistoricalYear-data.startYear)/(data.endYear-data.startYear)*100;
 return <div className="spatio-research annual-spatio">
 <section className="research-banner"><div><span className="control-label"><Layers3 size={15}/>{t('SPATIO-TEMPORAL / GLORICE')}</span><h2>{t('Watch harvested area change over time.')}</h2><p>{t('Explore annual maps from {p0} to {p1}.',{p0:data.startYear,p1:data.endYear})}</p></div><span className={`research-status ${historical?'':'projected'}`}><i/>{historical?t('HISTORICAL'):t('PROJECTED')}</span></section>
 <section className="card year-timeline"><div className="timeline-heading"><div><span className="control-label">{t('SELECT A YEAR')}</span><h3>{year}<small>{historical?t('Historical harvested area'):t('Annual model projection')}</small></h3></div><div className="timeline-playback"><button className="icon-button" aria-label={t('Previous year')} disabled={year===data.startYear} onClick={()=>chooseYear(year-1)}><ChevronLeft size={19}/></button><button className="outline-button" aria-label={playing?t('Pause timeline'):t('Play timeline')} onClick={()=>setPlaying(!playing)}>{playing?<Pause size={15}/>:<Play size={15}/>}<span>{playing?t('Pause'):t('Play')}</span></button><button className="icon-button" aria-label={t('Next year')} disabled={year===data.endYear} onClick={()=>chooseYear(year+1)}><ChevronRight size={19}/></button></div></div>
 <input className="spatio-year-slider" data-testid="spatio-year-slider" type="range" min={data.startYear} max={data.endYear} step="1" value={year} aria-label={t('Spatio-temporal year')} aria-valuetext={t('{p0} · {p1}',{p0:year,p1:historical?'Historical':'Projected'})} onChange={event=>chooseYear(Number(event.target.value))} style={{background:`linear-gradient(to right,#7b9e68 0%,#7b9e68 ${historicalPercent}%,#d7b374 ${historicalPercent}%,#d7b374 100%)`}}/>
 <div className="timeline-ticks">{[1961,1981,2001,2021,2030].map(value=><button key={value} style={{left:`${(value-data.startYear)/(data.endYear-data.startYear)*100}%`,transform:value===data.startYear?'none':value===data.endYear?'translateX(-100%)':'translateX(-50%)'}} onClick={()=>chooseYear(value)}>{value}</button>)}</div><div className="timeline-key"><span><i/>{t('Historical: {p0}–{p1}',{p0:data.startYear,p1:data.lastHistoricalYear})}</span><span><i/>{t('Projected: {p0}–{p1}',{p0:data.lastHistoricalYear+1,p1:data.endYear})}</span></div></section>
 <div className="card spatio-controls"><label>{t('Year')}<select aria-label={t('Choose timeline year')} value={year} onChange={event=>chooseYear(Number(event.target.value))}>{Array.from({length:data.endYear-data.startYear+1},(_,index)=>data.startYear+index).map(value=><option key={value} value={value}>{value}</option>)}</select></label><label>{t('Climate scenario')}<select aria-label={t('Spatial climate scenarios')} value={scenario} disabled={historical} onChange={event=>{setScenario(event.target.value);setPlaying(false)}}><option value="ssp245">{t('SSP2-4.5 · intermediate')}</option><option value="ssp585">{t('SSP5-8.5 · high emissions')}</option></select></label><label>{t('Analysis area')}<select aria-label={t('Spatio-temporal region')} value={selected} onChange={event=>setSelected(event.target.value)}><option value="ALL">{t('10 covered countries')}</option>{rows.map(row=><option key={row.code} value={row.code}>{countryName(row.code)}</option>)}</select></label><label>{t('Map layer')}<select aria-label={t('Harvested area layer')} value={historical?'mean':layer} onChange={event=>setLayer(event.target.value as Layer)}>{Object.entries(layerNames).map(([value,name])=><option key={value} value={value} disabled={historical&&value!=='mean'}>{t(name)}</option>)}</select></label><button className="outline-button" onClick={exportSelected}><Download size={15}/>{t('Export this year')}</button></div>
 {historical&&<p className="timeline-context">{t('Climate scenarios and uncertainty layers become available from 2022.')}</p>}
 <div className="spatio-map-grid"><section className="card"><div className="section-head"><div><h3>{t('Harvested-area map · {p0}',{p0:year})}</h3><p>{historical?t('GloRice historical distribution'):t('Model forecast on the existing rice-field pattern')}</p></div><button className="text-button" onClick={()=>setSelected('ALL')}>{t('Reset region')}</button></div><AnnualMap data={data} frame={frame} rows={rows} layer={historical?'mean':layer} selected={selected} onSelect={setSelected}/></section><section className="card spatio-detail"><span className="control-label">{t('SELECTED REGION')}</span><h3>{selected==='ALL'?t('ASEAN · 10 countries'):countryName(selected)}</h3><Sprout size={31} strokeWidth={1.2}/><div className="detail-row"><span>{t('Year')}</span><strong>{year}</strong></div><div className="detail-row"><span>{t('Harvested area')}</span><strong>{n(total.mean,2)} ha</strong></div>{!historical&&<><div className="detail-row"><span>{t('Lower estimate')}</span><strong>{n(total.lower,2)} ha</strong></div><div className="detail-row"><span>{t('Upper estimate')}</span><strong>{n(total.upper,2)} ha</strong></div></>}<p>{t('Country totals use the same GADM boundary fractions on a 2° grid in every year.')}</p>{['SGP','BRN'].includes(selected)&&<p className="small-country-note">{t('Small-country estimates are sensitive to the coarse grid. Interpret them cautiously.')}</p>}<p className="fine-print">{t('Harvested area is measured in hectares, not tonnes of rice or food available for consumption.')}</p></section></div>
 <div className="spatio-kpis"><div className="card"><span>{t('Harvested area · {p0}',{p0:year})}</span><strong>{n(total.mean/1e6,3)}<small>{t('million ha')}</small></strong><p>{selected==='ALL'?t('10 covered ASEAN countries'):countryName(selected)} · {historical?t('Historical'):scenario==='ssp245'?'SSP2-4.5':'SSP5-8.5'}</p></div><div className="card"><span>{t('Change from the previous year')}</span><strong>{change==null?'—':`${change>=0?'+':''}${n(change,2)}`}<small>{change==null?'':'%'}</small></strong><p>{change==null?t('No earlier comparable year available.'):t('Compared with {p0}',{p0:year-1})}</p></div><div className="card"><span>{t('Estimated range · {p0}',{p0:year})}</span><strong>{historical?'—':`${n((total.lower||0)/1e6,3)} – ${n((total.upper||0)/1e6,3)}`}<small>{historical?t('Historical data'):t('million ha')}</small></strong><p>{historical?t('Model uncertainty does not apply to historical map values.'):t('Sum of conditional cell bounds; not a regional confidence interval.')}</p></div></div>
 <section className="card annual-trend"><div className="section-head"><div><h3>{t('The annual trend')}</h3><p>{selected==='ALL'?t('10 covered ASEAN countries'):countryName(selected)} · {t('million ha')}</p></div><span className="mini-badge">{t('Selected year: {p0}',{p0:year})}</span></div><div className="annual-trend-canvas" role="img" aria-label={t('Annual harvested-area trend from 1961 to 2030')}><ResponsiveContainer width="100%" height="100%"><LineChart data={series} margin={{top:15,left:0,right:22,bottom:10}}><CartesianGrid vertical={false} strokeDasharray="3 5" stroke="#e3eadf"/><XAxis dataKey="year" type="number" domain={[data.startYear,data.endYear]} ticks={[1961,1981,2001,2021,2030]} tick={{fontSize:11}} tickLine={false} axisLine={false}/><YAxis tickFormatter={value=>n(value,1)} tick={{fontSize:11}} tickLine={false} axisLine={false} width={52}/><Tooltip formatter={(value,name)=>[`${n(Number(value),3)} ${t('million ha')}`,name==='past'?t('Historical'):t('Projected')]}/><ReferenceLine x={2021} stroke="#afbaa7" strokeDasharray="3 4"/><ReferenceLine x={year} stroke="#a78448"/><Line dataKey="past" stroke="#52876a" strokeWidth={2.5} dot={false} isAnimationActive={false}/><Line dataKey="future" stroke="#bd9b59" strokeDasharray="5 5" strokeWidth={2.5} dot={false} isAnimationActive={false}/></LineChart></ResponsiveContainer></div><p className="fine-print">{t('Solid line: historical. Dashed line: annual model projections. The vertical line marks your selected year.')}</p></section>
 <section className="card research-country-table"><div className="section-head"><div><h3>{t('Country results · {p0}',{p0:year})}</h3><p>{t('Select a country to highlight it on the map.')}</p></div><a className="text-button" href="/research/spatio-annual-countries.csv" download><Download size={15}/>{t('All years CSV')}</a></div><div className="table-scroll"><table><thead><tr><th>{t('Country')}</th><th>{t('Harvested area (ha)')}</th><th>{t('Lower estimate')}</th><th>{t('Upper estimate')}</th></tr></thead><tbody>{rows.map(row=><tr key={row.code} className={selected===row.code?'selected-row':''}><td><button className="country-link" onClick={()=>setSelected(row.code)}>{countries.find(country=>country.code===row.code)?.flag} {countryName(row.code)}</button></td><td>{n(row.mean,2)}</td><td>{n(row.lower,2)}</td><td>{n(row.upper,2)}</td></tr>)}</tbody></table></div></section>
 <div className="note-card"><Layers3 size={21}/><div><strong>{t('How to read the projected years')}</strong><p>{t('2022–2030 values are calculated year by year by the spatial-temporal model. Climate inputs gradually approach the CMIP6 average for 2021–2040; they are not forecasts of weather in individual years.')}</p><p>{t('Future fine-scale patterns follow GloRice 2021. The maps do not predict new rice-field locations. Timor-Leste is outside this analysis.')}</p></div></div>
 <details className="card annual-method"><summary><Activity size={17}/>{t('Model evaluation and data sources')}</summary><div><div className="research-metric-grid"><div><span>{t('R² · historical test')}</span><strong>{n(data.metrics.r2,3)}</strong><p>{t('Explained variation, not percentage accuracy.')}</p></div><div><span>{t('Average absolute error')}</span><strong>{n(data.metrics.mae_ha)}<small>ha</small></strong><p>{t('Per model grid cell')}</p></div><div><span>{t('Test observations')}</span><strong>{n(data.metrics.n_test)}</strong><p>{t('Unseen years 2012–2021')}</p></div></div><p>{t('The model was refitted on 1981–2021 data. Parameters were selected using 2007–2011 validation, followed by an independent 2012–2021 test. Uncertainty ranges remain conditional and do not include all climate uncertainty.')}</p><div className="annual-source-links">{data.sources.map(source=><a key={source.name} href={source.url} target="_blank" rel="noreferrer">{source.name}</a>)}</div></div></details>
 </div>;
}
