import { useEffect, useMemo, useState } from 'react';
import { Activity, BookOpen, Download, Expand, Layers3, MapPin, Sprout, X } from 'lucide-react';
import { CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { geoMercator, geoPath } from 'd3-geo';
import type { FeatureCollection } from 'geojson';
import research from './research.json';
import { countries } from './model.mjs';
import { spatioRows, spatioTotal } from './research-model.mjs';

type AreaRow = { code: string; name: string; mean: number; lower: number; upper: number; width: number };
type Layer = 'mean' | 'lower' | 'upper' | 'width';
const n = (value: number, digits = 0) => new Intl.NumberFormat('id-ID', { maximumFractionDigits: digits }).format(value);
const names: Record<Layer, string> = { mean: 'Estimasi luas panen', lower: 'Batas bawah', upper: 'Batas atas', width: 'Lebar interval' };
const scenarios = { ssp245: 'SSP2-4.5', ssp585: 'SSP5-8.5' };

function AreaMap({ rows, selected, layer, onSelect }: { rows: AreaRow[]; selected: string; layer: Layer; onSelect: (code: string) => void }) {
  const [geo, setGeo] = useState<FeatureCollection | null>(null);
  const [error, setError] = useState(false);
  const projection = useMemo(() => geoMercator().center([117, 9]).scale(430).translate([270, 164]), []);
  const path = geoPath(projection);
  useEffect(() => { fetch('/sea.geojson').then(r => { if (!r.ok) throw Error('map'); return r.json(); }).then(setGeo).catch(() => setError(true)); }, []);
  const fill = (row?: AreaRow) => {
    if (!row) return '#e3e8df';
    const value = row[layer];
    return value >= 5e6 ? '#285e48' : value >= 2e6 ? '#598d6b' : value >= 5e5 ? '#8bb78e' : value >= 1e5 ? '#b6cf9b' : '#dce8bd';
  };
  return <div className="area-map"><div className="map-tools"><span><MapPin size={13} />10 negara · hasil ringkasan GADM</span><span>2030 / hektare</span></div>{error ? <p className="empty-state">Peta tidak tersedia; tabel negara tetap dapat digunakan.</p> : !geo ? <p className="empty-state">Memuat batas negara…</p> : <svg viewBox="0 0 540 335" aria-label={`Peta ${names[layer]} per negara 2030`}>
    <rect width="540" height="335" rx="12" fill="#edf2e9" />
    {geo.features.map(feature => { const code = feature.properties?.code; const row = rows.find(r => r.code === code); return <path key={code} d={path(feature) || ''} fill={fill(row)} stroke={selected === code ? '#143e31' : '#fff'} strokeWidth={selected === code ? 2.5 : 1.2} className={row ? 'map-country' : ''} role={row ? 'button' : undefined} tabIndex={row ? 0 : undefined} aria-label={row ? `Luas panen ${row.name}` : undefined} onClick={() => row && onSelect(code)} onKeyDown={e => { if (row && ['Enter', ' '].includes(e.key)) { e.preventDefault(); onSelect(code); } }}><title>{row ? `${row.name}: ${n(row[layer])} ha` : feature.properties?.name}</title></path>; })}
    {rows.map(row => { const country = countries.find(c => c.code === row.code)!; const xy = projection(country.label as [number, number])!; return <text key={row.code} x={xy[0]} y={xy[1]} textAnchor="middle" className="area-map-label" pointerEvents="none">{country.name}</text>; })}
    {rows.filter(r => ['SGP', 'BRN'].includes(r.code)).map(row => { const country = countries.find(c => c.code === row.code)!; const xy = projection([country.lon, country.lat])!; return <circle key={row.code} cx={xy[0]} cy={xy[1]} r="5" fill={fill(row)} stroke="#fff" role="button" tabIndex={0} aria-label={`Titik luas panen ${country.name}`} onClick={() => onSelect(row.code)} onKeyDown={e => { if (['Enter', ' '].includes(e.key)) { e.preventDefault(); onSelect(row.code); } }}><title>{country.name}: {n(row[layer], 2)} ha</title></circle>; })}
  </svg>}<div className="area-legend"><span><i style={{background:'#dce8bd'}} />&lt;100 rb</span><span><i style={{background:'#b6cf9b'}} />100–500 rb</span><span><i style={{background:'#8bb78e'}} />0,5–2 jt</span><span><i style={{background:'#598d6b'}} />2–5 jt</span><span><i style={{background:'#285e48'}} />≥5 jt ha</span></div></div>;
}

export default function SpatioTemporal() {
  const [scenario, setScenario] = useState<'ssp245' | 'ssp585'>('ssp245');
  const [selected, setSelected] = useState('ALL');
  const [layer, setLayer] = useState<Layer>('mean');
  const [figure, setFigure] = useState('historical');
  const [expanded, setExpanded] = useState(false);
  const rows: AreaRow[] = spatioRows(research, scenario);
  const selectedRow = rows.find(row => row.code === selected);
  const total = selectedRow || spatioTotal(rows);
  const other: AreaRow[] = spatioRows(research, scenario === 'ssp245' ? 'ssp585' : 'ssp245');
  const otherTotal = selectedRow ? other.find(row => row.code === selected)! : spatioTotal(other);
  const item = research.spatio.figures.find(item => item.name === figure)!;
  const metrics = research.spatio.metrics;
  const meanMoran = research.spatio.residuals.reduce((sum, row) => sum + row.moran_i, 0) / research.spatio.residuals.length;
  useEffect(() => {
    if (!expanded) return;
    const previous = document.activeElement as HTMLElement | null;
    const oldOverflow = document.body.style.overflow;
    document.body.style.overflow = 'hidden';
    const button = document.querySelector<HTMLButtonElement>('.figure-dialog button'); button?.focus();
    const close = (event: KeyboardEvent) => { if (event.key === 'Escape') setExpanded(false); if (event.key === 'Tab') { event.preventDefault(); button?.focus(); } };
    document.addEventListener('keydown', close);
    return () => { document.body.style.overflow = oldOverflow; document.removeEventListener('keydown', close); previous?.focus(); };
  }, [expanded]);
  const exportSelected = () => {
    const filtered = selected === 'ALL' ? rows : rows.filter(row => row.code === selected);
    const csv = ['scenario,year,country,estimated_harvested_area_ha,conditional_lower_ha,conditional_upper_ha', ...filtered.map(row => [scenario, 2030, row.code, row.mean, row.lower, row.upper].join(','))].join('\r\n');
    const url = URL.createObjectURL(new Blob(['\uFEFF'+csv], {type:'text/csv;charset=utf-8'}));
    const anchor = document.createElement('a'); anchor.href=url; anchor.download=`riceguard-spatio-${scenario}-${selected}-2030.csv`; anchor.click(); URL.revokeObjectURL(url);
  };
  return <div className="spatio-research">
    <section className="research-banner"><div><span className="control-label"><Layers3 size={15} /> SPATIO-TEMPORAL / GLORICE</span><h2>Luas panen. Ruang. Waktu.</h2><p>Dynamic hurdle BYM2 + AR(1) · hasil notebook penelitian</p></div><span className="research-status"><i />OUTPUT TERSIMPAN</span></section>
    <div className="card spatio-controls"><label>Skenario iklim<select aria-label="Skenario iklim spasial" value={scenario} onChange={e => setScenario(e.target.value as typeof scenario)}><option value="ssp245">SSP2-4.5 · menengah</option><option value="ssp585">SSP5-8.5 · emisi tinggi</option></select></label><label>Wilayah analisis<select aria-label="Wilayah spatio-temporal" value={selected} onChange={e => setSelected(e.target.value)}><option value="ALL">10 negara dalam notebook</option>{rows.map(row => <option key={row.code} value={row.code}>{countries.find(c => c.code === row.code)?.name}</option>)}</select></label><label>Layer peta<select aria-label="Layer luas panen" value={layer} onChange={e => setLayer(e.target.value as Layer)}>{Object.entries(names).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label><button className="outline-button" onClick={exportSelected}><Download size={15} /> Ekspor pilihan</button></div>
    <div className="spatio-kpis"><div className="card"><span>Estimasi luas panen · 2030</span><strong>{n(total.mean/1e6, 3)}<small>juta ha</small></strong><p>{selectedRow ? countries.find(c => c.code === selected)?.name : 'Jumlah 10 negara ASEAN notebook'} · {scenarios[scenario]}</p></div><div className="card"><span>Interval bersyarat · 2030</span><strong>{n(total.lower/1e6, 3)} – {n(total.upper/1e6, 3)}<small>juta ha</small></strong><p>{selectedRow ? 'Batas hasil posterior aproksimatif' : 'Jumlah batas negara; bukan interval posterior total'}</p></div><div className="card"><span>Perbedaan skenario alternatif</span><strong>{n((otherTotal.mean / total.mean - 1)*100, 3)}<small>%</small></strong><p>Alternatif {scenario === 'ssp245' ? 'SSP5-8.5' : 'SSP2-4.5'} relatif terhadap pilihan</p></div></div>
    <div className="spatio-map-grid"><section className="card"><div className="section-head"><div><h3>Distribusi luas panen 2030</h3><p>{names[layer]} · {scenarios[scenario]} · ringkasan negara</p></div><button className="text-button" onClick={() => setSelected('ALL')}>Reset wilayah</button></div><AreaMap rows={rows} selected={selected} layer={layer} onSelect={setSelected} /></section><section className="card spatio-detail"><span className="control-label">WILAYAH TERPILIH</span><h3>{selectedRow ? countries.find(c => c.code === selected)?.name : 'ASEAN · 10 negara'}</h3><Sprout size={33} strokeWidth={1.2} /><div className="detail-row"><span>Estimasi</span><strong>{n(total.mean, 2)} ha</strong></div><div className="detail-row"><span>Batas bawah</span><strong>{n(total.lower, 2)} ha</strong></div><div className="detail-row"><span>Batas atas</span><strong>{n(total.upper, 2)} ha</strong></div><p>Sel model 2° dialokasikan menurut fraksi irisan batas GADM pada proyeksi equal-area. Geometri tampilan memakai Natural Earth.</p>{['SGP','BRN'].includes(selected) && <p className="small-country-note">Estimasi negara kecil sangat sensitif terhadap grid kasar dan batas wilayah. Gunakan untuk membaca hasil model.</p>}<p className="fine-print">Luas panen (ha) berbeda dari produksi gabah (ton). Hasil ini tidak langsung menentukan risiko atau defisit pangan.</p></section></div>
    <section className="card research-figures"><div className="section-head"><div><h3>Jejak perubahan dari raster asli</h3><p>Gambar tersimpan dari spatioASEAN.ipynb · tanpa mengarang nilai piksel</p></div><button className="icon-button" aria-label="Perbesar gambar penelitian" onClick={() => setExpanded(true)}><Expand size={18} /></button></div><div className="figure-tabs" role="group" aria-label="Pilihan visual penelitian">{research.spatio.figures.map(image => <button key={image.name} className={figure === image.name ? 'selected' : ''} onClick={() => setFigure(image.name)}>{image.name === 'historical' ? '1961 → 2021' : image.name === 'fine-2030' ? '2030 · 5 arcminute' : image.name === 'uncertainty' ? '2030 · Ketidakpastian' : 'Perbandingan negara'}</button>)}</div><button className="figure-preview" aria-label={`Perbesar ${item.title}`} onClick={() => setExpanded(true)}><img src={item.path} alt={item.title} /></button><div className="figure-caption"><p>{figure === 'historical' ? 'GloRice intensive harvested area: peta 1961 dan 2021 dengan skala log yang sama.' : figure === 'fine-2030' ? 'Pola 5 arcminute adalah disagregasi visual hasil grid 2° mengikuti dukungan luas panen GloRice 2021. Bukan inferensi baru pada piksel atau prediksi lokasi sawah baru.' : figure === 'uncertainty' ? 'Grid model 2°: dua skenario 2030 dan lebar interval SSP2-4.5. Interval bersyarat belum mencakup seluruh ketidakpastian iklim.' : 'Ringkasan negara berdasarkan fraksi irisan sel 2° dan batas GADM.'}</p><a href={item.path} download className="text-button"><Download size={14} /> PNG asli</a></div></section>
    <section className="card research-evaluation"><div className="section-head"><div><span className="control-label">MODEL / VALIDATION</span><h3>Kinerja yang dapat diperiksa</h3><p>Latih 1981–2011 · forward holdout 2012–2021 · {n(metrics.n_test)} observasi test</p></div><Activity size={20} /></div><div className="research-metric-grid"><div><span>R² pada holdout</span><strong>{n(metrics.r2, 4)}</strong><p>Koefisien determinasi · bukan % akurasi</p></div><div><span>MAE luas panen</span><strong>{n(metrics.mae_ha)}<small>ha</small></strong><p>RMSE {n(metrics.rmse_ha)} ha</p></div><div><span>Rerata Moran’s I residual</span><strong>{n(meanMoran, 3)}</strong><p>p = 0,005 per tahun · klaster masih tersisa</p></div></div><div className="residual-chart" role="img" aria-label="Grafik Moran I residual 2012 sampai 2021"><ResponsiveContainer width="100%" height="100%"><LineChart data={research.spatio.residuals} margin={{left:0,right:25,top:15,bottom:10}}><CartesianGrid stroke="#e5e9e1" strokeDasharray="3 5" vertical={false}/><XAxis dataKey="year" tick={{fontSize:11}} axisLine={false} tickLine={false}/><YAxis domain={[0,1]} tick={{fontSize:11}} axisLine={false} tickLine={false}/><Tooltip formatter={v => [n(Number(v),4),'Moran’s I']}/><Line dataKey="moran_i" stroke="#548467" strokeWidth={2.4} dot={{r:4}} isAnimationActive={false}/></LineChart></ResponsiveContainer></div><div className="research-notes"><BookOpen size={19}/><div><strong>R² tinggi tetap disertai pola residual spasial.</strong><p>Moran’s I positif menunjukkan galat yang masih berkelompok secara spasial. Bias aktual − prediksi: {n(metrics.bias_actual_minus_pred_ha)} ha; model cenderung melebihkan luas panen pada holdout. Presence ROC AUC = {n(metrics.presence_roc_auc, 2)}.</p><p>Untuk proyeksi, notebook melatih ulang GloRice 1981–2021 dan memakai satu GCM, ACCESS-CM2. “2030” mewakili rerata iklim 2021–2040. Interval merupakan posterior aproksimatif luas panen bersyarat, bukan keseluruhan ketidakpastian skenario.</p></div></div></section>
    <section className="card research-country-table"><div className="section-head"><div><h3>Ringkasan negara · {scenarios[scenario]}</h3><p>2030 · hektare · klik negara untuk memeriksa hasil</p></div><a className="text-button" href="/research/spatio-countries-2030.csv" download><Download size={15}/> Kedua skenario</a></div><div className="table-scroll"><table><thead><tr><th>NEGARA</th><th>ESTIMASI</th><th>BATAS BAWAH</th><th>BATAS ATAS</th><th>LEBAR INTERVAL</th></tr></thead><tbody>{rows.map(row => <tr key={row.code} className={selected === row.code ? 'selected-row' : ''}><td><button className="country-link" onClick={() => setSelected(row.code)}>{countries.find(c => c.code === row.code)?.flag} {countries.find(c => c.code === row.code)?.name}</button></td><td>{n(row.mean,2)}</td><td>{n(row.lower,2)}</td><td>{n(row.upper,2)}</td><td>{n(row.width,2)}</td></tr>)}</tbody></table></div></section>
    <div className="note-card"><Layers3 size={21}/><div><strong>Cakupan penelitian dan file sumber.</strong><p>Ringkasan ini memuat 10 negara dalam notebook, termasuk Singapura dan Brunei; Timor-Leste tidak tercakup. Jumlah estimasi negara {n(spatioTotal(rows).mean/1e6,2)} juta ha berbeda dari seluruh grid {n(research.spatio.gridSummary.find(r => r.scenario === scenario)!.total_predicted_area_ha/1e6,2)} juta ha karena grid juga meliputi daratan di luar ASEAN. Penjumlahan batas negara bukan interval posterior total kawasan.</p><p>Output notebook sudah terintegrasi. CSV/GeoTIFF grid mentah, data GloRice, kovariat iklim, dan model terlatih belum tersedia di direktori. Peta piksel ditampilkan sebagai gambar asli; nilai interaktif memakai tabel negara yang tersimpan. Bagian APRA500 legacy tidak digunakan.</p></div></div>
    {expanded && <div className="modal-backdrop" onClick={() => setExpanded(false)}><div className="figure-dialog" role="dialog" aria-modal="true" aria-label={item.title} onClick={e => e.stopPropagation()}><div><h3>{item.title}</h3><button className="icon-button" aria-label="Tutup gambar penelitian" onClick={() => setExpanded(false)}><X size={22}/></button></div><img src={item.path} alt={item.title}/></div></div>}
  </div>;
}
